import Head from 'next/head'
import { GraphQLClient, gql } from 'graphql-request'
import BlogCard from '../components/BlogCard';
import Navbar from '../components/Navbar';
import Banner from '../components/Banner';
import Footer from '../components/Footer';

const graphcms = new GraphQLClient(
  'https://api-eu-west-2.hygraph.com/v2/cl5z9pdqb2zjg01ut4ql1d7ib/master'
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
        text
      }
      coverPhoto {
        url
        publishedAt
        createdBy {
          id
        }
      }
      author {
        name
        author {
          url
        }
      }
    }
  }
`

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY)
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}

export default function Home({posts}) {
  return (
    <div className="container">
      <Head>
        <title>Ola's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Navbar />
        <Banner />

        <section className='blogcards'>
          {posts.map((post) => (
            <BlogCard 
            title = {post.title}
            author = {post.author}
            coverPhoto = {post.coverPhoto}
            key={post.id}
            datePublished = {post.datePublished}
            slug = {post.slug}
            content = {post.content}
            />
          ))}
        </section>

        <Footer />
        
      </main>
      

    </div>
  )
}
